### ISSUE TITLE
Thunderdome 2022 link broken

### ISSUE THREAD

**Issue by jamescollinsDA** [koechlm/Vault-Thunderdome#3]
Hi Markus,
The link to 2022 Thunderdome is broken: _(For Thunderdome Sample 2022 and newer goto: https://github.com/koechlm/Vault-Thunderdome-Sample)_
We will be migrating to 2022 and it would be great to have the Thunderdome addin.
Thanks,
James

**Comment by koechlm** [comment]
Hello James,
the link isn't broken; the target repository has been private so far. I changed to public.

**Comment by jamescollinsDA** [comment]
Thankyou Markus.
