### ISSUE TITLE
Thunderdome could not successfully execute

### ISSUE THREAD

**Issue by gordondfg** [koechlm/Vault-Thunderdome#4]
Hi
we recently updated to Vault 2024 and installed Thunderdome 2024. It has been working fine but I am now coming across an error after click yes to update when logging into vault we get Thunderdome could not successfully execute update. Could not find files.
I have reinstalled, have full permissions to the temp folder.  This is now happening on every new install.
Any help would be appreciated
Thanks
Diane

![error](https://github.com/koechlm/Vault-Thunderdome/assets/171940823/61425657-ef5b-4bda-add5-2fb3a81a4f5e)

**Comment by koechlm** [comment]
There is an issue with your configuration or access control. Is the file Deployment.td accessible and downloaded? In other words, can you find the *td file in the temp folder?
You need to debug if the file downloads but can't be accessed later in the code.

**Comment by koechlm** [comment]
@gordondfg: I just realized that this issue is posted in the legacy project. It ended with the 2020 release. The latest code base is here: https://github.com/koechlm/Vault-Thunderdome-Sample
